"""TiDB Lightning config emission and invocation.

Security: TiDB password is NOT inlined in the TOML — supplied via the
TIDB_LIGHTNING_TIDB_PASSWORD env var at runtime. TOML file is chmod 600.
"""

from __future__ import annotations

import logging
import os
import stat
import subprocess
from pathlib import Path

from tishift_mongodb.config import TiShiftConfig


log = logging.getLogger(__name__)

_PASSWORD_PLACEHOLDER = "${TIDB_LIGHTNING_TIDB_PASSWORD}"


def build_lightning_config(
    cfg: TiShiftConfig, *, output_path: str | Path = "tishift-output/tidb-lightning.toml"
) -> Path:
    """Emit a tidb-lightning.toml referencing the staging URL.

    The staging URL is whatever the config specified — s3, gs, azure, or local.
    Lightning reads any of those directly.
    """
    data_source_dir = cfg.load.staging.base_url.rstrip("/")

    toml = f"""# tidb-lightning.toml — generated by tishift-mongodb
# Password supplied via TIDB_LIGHTNING_TIDB_PASSWORD env var; never inlined.
[mydumper]
data-source-dir = "{data_source_dir}"

[tikv-importer]
backend = "{cfg.load.lightning.backend}"
sorted-kv-dir = "{cfg.load.lightning.sorted_kv_dir}"

[tidb]
host = "{cfg.target.host}"
port = {cfg.target.port}
user = "{cfg.target.user}"
# password supplied via {_PASSWORD_PLACEHOLDER}

[[mydumper.files]]
pattern = '^(?P<table>[^/]+)/part-.*\\.ndjson$'
type = 'ndjson'
"""

    if cfg.load.lightning.pd_addr:
        toml += f'\n[tikv-importer]\npd-addr = "{cfg.load.lightning.pd_addr}"\n'

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(toml)
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    log.info("Wrote Lightning config to %s (mode 600)", path)
    return path


def run_lightning(
    config_path: str | Path, *, tidb_password: str | None = None
) -> int:
    """Invoke tidb-lightning. Password via env, never logged.

    Raises if TIDB_LIGHTNING_TIDB_PASSWORD isn't set and no arg provided.
    """
    if tidb_password is not None:
        child_env = dict(os.environ)
        child_env["TIDB_LIGHTNING_TIDB_PASSWORD"] = tidb_password
    elif "TIDB_LIGHTNING_TIDB_PASSWORD" not in os.environ:
        raise RuntimeError(
            "TIDB_LIGHTNING_TIDB_PASSWORD env var not set and no tidb_password arg provided."
        )
    else:
        child_env = None

    cmd = ["tidb-lightning", "-config", str(config_path)]
    log.info("Running %s (password via env)", " ".join(cmd))
    proc = subprocess.run(cmd, check=False, env=child_env)
    return proc.returncode
