"""TiDB Lightning configuration and invocation.

Security note: tidb-lightning's TOML format includes the TiDB password
in the `[tidb]` section. We never write that file with the password
inlined. Instead, the TOML uses a placeholder and the password is
delivered to Lightning via the `TIDB_LIGHTNING_TIDB_PASSWORD`
environment variable, which Lightning reads at runtime.

The generated TOML file is also chmod 600 so that only the running user
can read it.
"""

from __future__ import annotations

import logging
import os
import stat
import subprocess
from pathlib import Path

from tishift_firestore.config import TiShiftConfig
from tishift_firestore.core.load.dataflow_runner import LoadState


log = logging.getLogger(__name__)


_PASSWORD_PLACEHOLDER = "${TIDB_LIGHTNING_TIDB_PASSWORD}"


def build_lightning_config(
    cfg: TiShiftConfig,
    *,
    state: LoadState,
    output_path: str | Path = "tishift-output/tidb-lightning.toml",
) -> Path:
    """Emit a tidb-lightning.toml that ingests the NDJSON files from the Dataflow output.

    Lightning's `local` (physical) backend writes SST files directly to TiKV via PD.
    The data-source-dir must point at the GCS root containing one subdir per table.

    The TiDB password is NOT inlined — it must be supplied via the
    TIDB_LIGHTNING_TIDB_PASSWORD env var at run_lightning() time. This avoids
    persisting the credential to disk in plaintext.
    """
    completed_paths = [j.gcs_path for j in state.jobs.values() if j.status == "complete"]
    if not completed_paths:
        raise RuntimeError("No completed Dataflow jobs to ingest.")

    data_source_dir = (
        f"gs://{cfg.source.staging.gcs_bucket}/{cfg.source.staging.gcs_prefix}"
    )

    toml = f"""# tidb-lightning.toml — generated by tishift-firestore
# Password is supplied via TIDB_LIGHTNING_TIDB_PASSWORD env var at runtime,
# never inlined into this file.
[mydumper]
data-source-dir = "{data_source_dir}"

[tikv-importer]
backend = "{cfg.load.lightning.backend}"
sorted-kv-dir = "{cfg.load.lightning.sorted_kv_dir}"

[tidb]
host = "{cfg.target.host}"
port = {cfg.target.port}
user = "{cfg.target.user}"
# password supplied via {_PASSWORD_PLACEHOLDER}

[[mydumper.files]]
pattern = '^(?P<table>[^/]+)/part-.*\\.ndjson$'
type = 'ndjson'
"""

    if cfg.load.lightning.pd_addr:
        toml += f'\n[tikv-importer]\npd-addr = "{cfg.load.lightning.pd_addr}"\n'

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(toml)
    # chmod 600 — only the running user can read. Mitigates the case where
    # data_source_dir or host names accidentally embed sensitive context
    # (e.g., a hostname containing a project ID the operator wants kept tight).
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    log.info("Wrote Lightning config to %s (mode 600)", path)
    return path


def run_lightning(
    config_path: str | Path, *, tidb_password: str | None = None
) -> int:
    """Invoke `tidb-lightning -config <path>`. Returns the exit code.

    `tidb-lightning` must be on PATH. The TiDB password is passed via the
    TIDB_LIGHTNING_TIDB_PASSWORD env var. If `tidb_password` is None,
    the env var must already be set in the parent process.

    The password environment variable is passed only to the child Lightning
    process — it is never logged, never echoed in `Running ...` output.
    """
    if tidb_password is not None:
        child_env = dict(os.environ)
        child_env["TIDB_LIGHTNING_TIDB_PASSWORD"] = tidb_password
    elif "TIDB_LIGHTNING_TIDB_PASSWORD" not in os.environ:
        raise RuntimeError(
            "TIDB_LIGHTNING_TIDB_PASSWORD env var not set and no tidb_password "
            "argument provided. Lightning will not be able to authenticate."
        )
    else:
        child_env = None  # inherit unchanged

    cmd = ["tidb-lightning", "-config", str(config_path)]
    log.info("Running %s (password supplied via env)", " ".join(cmd))
    proc = subprocess.run(cmd, check=False, env=child_env)
    return proc.returncode
